name: camera_image_selector
description: "Plugin to select Images from Camera and Gallery"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.6.2 <4.0.0'  # Update SDK constraints
  flutter: '>=3.16.0'     # Update Flutter version

dependencies:
  flutter:
    sdk: flutter
  camera: 0.10.6
  image_picker: ^1.0.7
  plugin_platform_interface: ^2.1.8
  image_editor_plus: ^1.0.6
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.camera_image_selector
        dartPluginClass: CameraImageSelector
      ios:
        dartPluginClass: CameraImageSelector

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - packages/camera_image_selector/assets/NoImage.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
